### ISSUE TITLE
TMC2209 on GT2560

### ISSUE THREAD

**Issue by nexius76** [GusBricker/GeeetechA10_Klipper#1]
Hello, Gus.... I really need and help. I don't know how to use a TMC2209 UART, in legacy mode with a GT2560 v4.0. Can you help me?

**Comment by GusBricker** [comment]
Hello,

I dont think you can use UART on GT2560 v4 as the PCB doesnt bring out these pins to the TMC2209. The only way would be with some sort of software UART which I am unsure if Klipper supports. Perhaps look at the Klipper documentation.

**Comment by nexius76** [comment]
Thanks for you answare so do you confirm that I need to change my 2209 UART with 2209 Standalone?

**Comment by GusBricker** [comment]
I believe it will only work in standalone.
